# Generated by Django 4.1.3 on 2022-12-09 18:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Departments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deprtName', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name_plural': 'Departments Detail',
            },
        ),
        migrations.CreateModel(
            name='EmployeeDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('doj', models.DateField()),
                ('departmentName', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='employeeDT', to='projectApp.departments')),
            ],
            options={
                'verbose_name_plural': 'Employees Detail',
            },
        ),
        migrations.CreateModel(
            name='ProjectDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('projectName', models.CharField(max_length=1000)),
                ('projectStartDate', models.DateField()),
                ('projectEndDate', models.DateField()),
                ('projectManagerName', models.CharField(max_length=100)),
                ('employeesNames', models.ManyToManyField(related_name='projectDT', to='projectApp.employeedetails')),
            ],
            options={
                'verbose_name_plural': 'Project Details',
            },
        ),
    ]
