# Generated by Django 4.1.3 on 2022-12-10 07:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projectApp', '0002_employeedetails_designationflag_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeedetails',
            name='designationFlag',
            field=models.CharField(blank=True, choices=[('Project Manager', 'Project Manger')], max_length=20, null=True),
        ),
        migrations.RemoveField(
            model_name='projectdetails',
            name='employeesNames',
        ),
        migrations.AddField(
            model_name='projectdetails',
            name='employeesNames',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='projectDT', to='projectApp.employeedetails'),
        ),
    ]
