# Generated by Django 4.1.3 on 2022-12-10 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projectApp', '0003_alter_employeedetails_designationflag_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employeedetails',
            name='designationFlag',
        ),
        migrations.AddField(
            model_name='employeedetails',
            name='isProjectManager',
            field=models.BooleanField(default=False),
        ),
    ]
