# Generated by Django 4.1.3 on 2022-12-10 15:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projectApp', '0004_remove_employeedetails_designationflag_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectdetails',
            name='projectManagerName',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='projectDTP', to='projectApp.employeedetails'),
        ),
    ]
