# Generated by Django 4.1.3 on 2022-12-10 15:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projectApp', '0005_alter_projectdetails_projectmanagername'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='projectdetails',
            name='projectManagerName',
        ),
        migrations.AddField(
            model_name='projectdetails',
            name='projectManager',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='projectDTP', to='projectApp.employeedetails'),
        ),
    ]
