# Generated by Django 4.1.3 on 2022-12-10 16:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projectApp', '0008_projectdetails_projectmanager'),
    ]

    operations = [
        migrations.RenameField(
            model_name='projectdetails',
            old_name='employeesNames',
            new_name='employeeName',
        ),
    ]
